<?xml version="1.0" encoding="utf-8"?><Database Name="CrudDB" Class="InvoiceClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TIELT120;Initial Catalog=CrudDB;User ID=sa" SettingsObjectName="CrudDA.Properties.Settings" SettingsPropertyName="CrudDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="idInvoice" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Concept" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="dateI" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dateF" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceLine" Member="InvoiceLines" ThisKey="idInvoice" OtherKey="rIdInvoice" Type="InvoiceLine" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceLine" Member="InvoiceLines">
    <Type Name="InvoiceLine">
      <Column Name="idLine" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rIdInvoice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sDesc" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_InvoiceLine" Member="Invoice" ThisKey="rIdInvoice" OtherKey="idInvoice" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
</Database>